### ISSUE TITLE
0x6

### ISSUE THREAD

**Issue by letter4152** [L8X/Roblox-Client-Optimizer#51] opened 2023-04-22 00:36 UTC
i reinstalled roblox a bunch of times idk what to do

![image](https://user-images.githubusercontent.com/131500178/233752302-b1fbc89f-dc5f-4e58-b38e-e2bce00a5275.png)

**Comment by sehmatary** [comment] 2023-04-22 00:47
it's happening to me too
![image](https://user-images.githubusercontent.com/131500581/233752829-c7aee33b-605b-40a4-9998-78295d23bfb7.png)

**Comment by Kaiddd** [comment] 2023-04-22 01:04
@L8X you able to reproduce?

**Comment by Kaiddd** [comment] 2023-04-22 01:21
I'll figure it out when I'm on pc...

**Comment by 3x333** [comment] 2023-04-22 01:24
Happening here too, Roblox version: version-8a11605ad3eb413a

**Comment by Piesel22** [comment] 2023-04-22 08:57
The same happens on my computer and it's not just RCO, it also affects rbxfpsunlocker and roblox executors for cheating

**Comment by Piesel22** [comment] 2023-04-22 10:39
Same here

**Comment by NotKendolaser** [comment] 2023-04-22 11:07
its because of byfron you can remove it

**Comment by letter4152** [comment] 2023-04-22 13:03
is there anything i could do roblox without an fps unlocker is hell

**Comment by SoleyforGithub** [comment] 2023-04-22 15:29
This is a bug and it will be fixed right?

**Comment by EBTheNameLess** [comment] 2023-04-22 15:49
Still we can manually put the ClientAppSettings.json into the file until rco is fixed

**Comment by SoleyforGithub** [comment] 2023-04-22 16:00
> at least we can manually put the ClientAppSettings.json into the file until rco is fixed

It doesn't work for me, it doesnt have .json at the end and it wont work no matter how i try can you please help if you can?

**Comment by SoleyforGithub** [comment] 2023-04-22 16:08
Nvm, i figured it out somehow

**Comment by Kaiddd** [comment] 2023-04-22 17:24
Fix will be in 2.1.0, perhaps even a hotfix 2.0.3

**Comment by Laqota** [comment] 2023-04-22 21:53
happens to me as well.

**Comment by Kaiddd** [comment] 2023-04-23 02:55
#63

**Comment by Kaiddd** [comment] 2023-04-23 02:57
Better explained in #63 
Will fix tonight

**Closed by Kaiddd** 2023-04-23 02:57 UTC
Labels: bug, waiting for data
