### ISSUE TITLE
Roblox install is outdated

### ISSUE THREAD

**Issue by zwamiii** [L8X/Roblox-Client-Optimizer#61] opened 2023-04-22 22:30 UTC
When I try the installer it says "Your Roblox install is outdated". And I've deleted and reinstalled roblox multiple times. And Still nothing is working. I've also tried doing it by naming the folder CilentSettings and putting the CilentAppSettings.json in the folder and that also doesn't work.

**Comment by Kaiddd** [comment] 2023-04-22 22:48
Duplicate of #51

**Closed** 2023-04-22 22:48 UTC
